In [ ]:
# test tensorflow nonzero indices
import tensorflow as tf

# # tensor = tf.random.uniform([4,2,5, 2])
# tensor = tf.zeros([4,2,5, 2])
# print(tensor)

In [ ]:
non_zeros =  tf.greater(tensor, 1e-7)
print(non_zeros)

In [ ]:
non_zeros =  tf.math.less(tensor, 1e-7)
print(non_zeros)

In [ ]:
non_zero_array = tf.boolean_mask(tensor, non_zeros)
print(non_zero_array)

In [ ]:
tensor = tf.zeros([4,2,5, 2])
non_zeros =  tf.greater(tensor, 1e-7)
indices = tf.where(non_zeros)
print(indices)
is_empty =  tf.equal(tf.size(indices),0)
print(is_empty)

if is_empty:
    print("empty")

In [ ]:
import tensorflow as tf

tensor = tf.random.uniform([2,2])
print(tensor)
tensor_reshape = tf.reshape(tensor, [-1, 1])
print(tensor_reshape)
fulfill_bool =  tf.greater(tensor_reshape, 0.5)
# indices = tf.where(non_zeros)
print("fulfill_bool",fulfill_bool)
num_tp =  tf.math.reduce_sum(tf.cast(non_zeros_bool, tf.float32))
# print(num_tp)
idx_replace = tf.where( fulfill_bool == True )
idx_keep =  tf.where(fulfill_bool == False)
print("idx_replace:", idx_replace)
print("idx_keep:", idx_keep)
# print("idx_replace:", idx_replace[:,-1])

value_need_replace =  tf.gather( tensor_reshape, idx_replace )
print("value_need_replace:", value_need_replace, value_need_replace.shape )
value_for_replace =  tf.zeros(tf.shape(value_need_replace))
print("value_for_replace:", value_for_replace)
value_need_keep =  tf.gather( tensor_reshape, idx_keep )

print("value_need_keep:", value_need_keep, value_need_keep.shape)

# value_for_replace = range(value_need_replace.shape[0])
# value_need_keep = range(value_need_keep.shape[0])
print("value_for_replace[:,-1]:",value_for_replace[:,-1])
print("value_need_keep[:, -1]:", value_need_keep[:,-1])
replaced_tensor =  tf.where(fulfill_bool, x=value_for_replace[:,-1], y= value_need_keep[:, -1] )
# replaced_tensor =  tf.where(fulfill_bool, x=value_for_replace, y= value_need_keep)
print("replaced_tensor:", replaced_tensor)
# replace the value larger than 0.5 , tf where   true replaced with x, else flse replaced with y
# replaced_tensor = tf.where(fulfill_bool, x=)

In [67]:
import tensorflow as tf

tensor = tf.reshape(tf.random.uniform([2,4]), [1,-1])
condition = tf.greater(tensor, 0.5)
true_indices = tf.where(condition)

# case_true = tf.reshape(tf.multiply(tf.ones([8], tf.int32), -9999), [2, 4])
case_true1 = tf.reshape(tf.random.uniform([true_indices.shape[0]]), [1, -1])
zeros_paddings =  tf.reshape(tf.tile([0.0],[tf.shape(tensor)[-1]- tf.shape(case_true1)[-1]]), [1, -1])
case_true2 = tf.concat([case_true1, zeros_paddings], -1)
case_false = tensor
a_m = tf.where(condition, case_true2, case_false)

print("tensor:",tensor)
# print("case_true1:", case_true1)
print("zeros_paddings:", zeros_paddings)

print(condition)
print(true_indices)
print("case_true2:", case_true2)

print("a_m:", a_m)

tensor: tf.Tensor(
[[0.5312946  0.24023116 0.17054498 0.60127366 0.38026917 0.6890931
  0.06935036 0.06791604]], shape=(1, 8), dtype=float32)
zeros_paddings: tf.Tensor([[0. 0. 0. 0. 0.]], shape=(1, 5), dtype=float32)
tf.Tensor([[ True False False  True False  True False False]], shape=(1, 8), dtype=bool)
tf.Tensor(
[[0 0]
 [0 3]
 [0 5]], shape=(3, 2), dtype=int64)
case_true2: tf.Tensor(
[[0.7033702  0.26692116 0.1315105  0.         0.         0.
  0.         0.        ]], shape=(1, 8), dtype=float32)
a_m: tf.Tensor(
[[0.7033702  0.24023116 0.17054498 0.         0.38026917 0.
  0.06935036 0.06791604]], shape=(1, 8), dtype=float32)


In [95]:
import tensorflow as tf

tensor = tf.random.uniform([2,4])
condition = tf.greater(tensor, 0.5)
idx_replace = tf.where( condition == True )
idx_keep =  tf.where(condition == False)


value_need_replace = tf.random.uniform([idx_replace.shape[0]])

value_need_keep =  tf.gather_nd( tensor, idx_keep )

print("tensor:",tensor)
print("idx_replace:", idx_replace)
print("value_need_replace:", value_need_replace)
print("value_need_keep:", value_need_keep)
print("tensor shape:", tf.shape(tensor))  ### here shape is int 32, diretly use tensor.shape
value_for_replace =  tf.sparse.to_dense(tf.sparse.SparseTensor(idx_replace,value_need_replace, tensor.shape ))

print("value_for_replace:", value_for_replace)


case_false = tensor
a_m = tf.where(condition, value_for_replace, case_false)
print(condition)


print("replacedTensor:", a_m)

tensor: tf.Tensor(
[[0.4914465  0.93643427 0.94141793 0.8817053 ]
 [0.75902987 0.8223671  0.06045377 0.05763388]], shape=(2, 4), dtype=float32)
idx_replace: tf.Tensor(
[[0 1]
 [0 2]
 [0 3]
 [1 0]
 [1 1]], shape=(5, 2), dtype=int64)
value_need_replace: tf.Tensor([0.8194101  0.39099038 0.36934757 0.33711576 0.24898577], shape=(5,), dtype=float32)
value_need_keep: tf.Tensor([0.4914465  0.06045377 0.05763388], shape=(3,), dtype=float32)
tensor shape: tf.Tensor([2 4], shape=(2,), dtype=int32)
value_for_replace: tf.Tensor(
[[0.         0.8194101  0.39099038 0.36934757]
 [0.33711576 0.24898577 0.         0.        ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[False  True  True  True]
 [ True  True False False]], shape=(2, 4), dtype=bool)
replacedTensor: tf.Tensor(
[[0.4914465  0.8194101  0.39099038 0.36934757]
 [0.33711576 0.24898577 0.06045377 0.05763388]], shape=(2, 4), dtype=float32)


In [30]:
row =  indices[:,1]/4
colom =  indices[:, 2]
# y1 =  indices[0][1]
print(row)

NameError: name 'indices' is not defined

In [ ]:
centroidsx =  2
centroidsy =  3

In [ ]:
all_x =  indices[:, 0]
print(all_x)
all_y =  indices[:, 1]
print(all_y)

In [ ]:
distance_all_x= all_x -centroidsx 
print("distance_all_x:", distance_all_x)

In [ ]:
distnace_all_x_squre =  tf.math.square(distance_all_x)
print("distnace_all_x_squre:", distnace_all_x_squre)

In [ ]:
distance_all_y =  all_y-centroidsy
print("distance_all_y:", distance_all_y)

In [ ]:
distnace_all_y_squre =  tf.math.square(distance_all_y)
print("distnace_all_y_squre:", distnace_all_y_squre)

In [ ]:
all_squre_distance = distnace_all_x_squre + distnace_all_y_squre
print("all_squre_distance:", all_squre_distance)

In [ ]:
distances_all_nonzeros =  tf.math.sqrt(tf.cast(all_squre_distance, tf.float32))
print("distances_all_nonzeros", distances_all_nonzeros)

In [ ]:
max_dis =  tf.math.reduce_max(distances_all_nonzeros)
print("max_dis:", max_dis)

In [ ]:
a = tf.constant([0.5])
b =  tf.constant([0.4])

min = tf.math.reduce_min([a, b])
print(min)
max = tf.math.reduce_max([a, b])
print(max)