In [1]:
# test tensorflow nonzero indices
import tensorflow as tf

# tensor = tf.random.uniform([4,2,5, 2])
tensor = tf.zeros([4,2,5, 2])
print(tensor)

--AA
AA--
tf.Tensor(
[[[[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]]], shape=(4, 2, 5, 2), dtype=float32)


In [ ]:
non_zeros =  tf.greater(tensor, 1e-7)
print(non_zeros)

In [ ]:
non_zeros =  tf.math.less(tensor, 1e-7)
print(non_zeros)

In [ ]:
non_zero_array = tf.boolean_mask(tensor, non_zeros)
print(non_zero_array)

In [10]:
tensor = tf.zeros([4,2,5, 2])
non_zeros =  tf.greater(tensor, 1e-7)
indices = tf.where(non_zeros)
print(indices)
is_empty =  tf.equal(tf.size(indices),0)
print(is_empty)

if is_empty:
    print("empty")

tf.Tensor([], shape=(0, 4), dtype=int64)
tf.Tensor(True, shape=(), dtype=bool)
empty


In [8]:
tensor = tf.random.uniform([2,3])
print(tensor)
non_zeros_bool =  tf.greater(tensor, 0.5)
# indices = tf.where(non_zeros)
print(non_zeros_bool)
num_tp =  tf.math.reduce_sum(tf.cast(non_zeros_bool, tf.float32))
print(num_tp)


tf.Tensor(
[[0.25429833 0.66988635 0.18512201]
 [0.8488308  0.693854   0.31845367]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[False  True False]
 [ True  True False]], shape=(2, 3), dtype=bool)
tf.Tensor(3.0, shape=(), dtype=float32)


In [ ]:
row =  indices[:,1]/4
colom =  indices[:, 2]
# y1 =  indices[0][1]
print(row)

In [ ]:
centroidsx =  2
centroidsy =  3

In [ ]:
all_x =  indices[:, 0]
print(all_x)
all_y =  indices[:, 1]
print(all_y)

In [ ]:
distance_all_x= all_x -centroidsx 
print("distance_all_x:", distance_all_x)

In [ ]:
distnace_all_x_squre =  tf.math.square(distance_all_x)
print("distnace_all_x_squre:", distnace_all_x_squre)

In [ ]:
distance_all_y =  all_y-centroidsy
print("distance_all_y:", distance_all_y)

In [ ]:
distnace_all_y_squre =  tf.math.square(distance_all_y)
print("distnace_all_y_squre:", distnace_all_y_squre)

In [ ]:
all_squre_distance = distnace_all_x_squre + distnace_all_y_squre
print("all_squre_distance:", all_squre_distance)

In [ ]:
distances_all_nonzeros =  tf.math.sqrt(tf.cast(all_squre_distance, tf.float32))
print("distances_all_nonzeros", distances_all_nonzeros)

In [ ]:
max_dis =  tf.math.reduce_max(distances_all_nonzeros)
print("max_dis:", max_dis)

In [ ]:
a = tf.constant([0.5])
b =  tf.constant([0.4])

min = tf.math.reduce_min([a, b])
print(min)
max = tf.math.reduce_max([a, b])
print(max)