In [44]:
# test tensorflow nonzero indices
import tensorflow as tf

# tensor = tf.random.uniform([4,2,5, 2])
tensor = tf.zeros([4,2,5, 2])
print(tensor)

tf.Tensor(
[[[[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]]], shape=(4, 2, 5, 2), dtype=float32)


In [45]:
non_zeros =  tf.greater(tensor, 1e-7)
print(non_zeros)

tf.Tensor(
[[[[False False]
   [False False]
   [False False]
   [False False]
   [False False]]

  [[False False]
   [False False]
   [False False]
   [False False]
   [False False]]]


 [[[False False]
   [False False]
   [False False]
   [False False]
   [False False]]

  [[False False]
   [False False]
   [False False]
   [False False]
   [False False]]]


 [[[False False]
   [False False]
   [False False]
   [False False]
   [False False]]

  [[False False]
   [False False]
   [False False]
   [False False]
   [False False]]]


 [[[False False]
   [False False]
   [False False]
   [False False]
   [False False]]

  [[False False]
   [False False]
   [False False]
   [False False]
   [False False]]]], shape=(4, 2, 5, 2), dtype=bool)


In [46]:
# non_zero_array = tf.boolean_mask(tensor, non_zeros)
# print(non_zero_array)

In [48]:
indices = tf.where(non_zeros)

print(indices)
if indices.numpy().size:
    print(indices)
else:
    print("empty")
    

tf.Tensor([], shape=(0, 4), dtype=int64)
empty


In [41]:
row =  indices[:,1]/4
colom =  indices[:, 2]
# y1 =  indices[0][1]
print(row)

tf.Tensor(
[0.   0.   0.   0.   0.   0.   0.   0.   0.25 0.25 0.25 0.25 0.25 0.25
 0.25 0.25 0.   0.   0.   0.   0.   0.   0.   0.   0.25 0.25 0.25 0.25
 0.25 0.25 0.25 0.25], shape=(32,), dtype=float64)


In [6]:
centroidsx =  2
centroidsy =  3

In [7]:
all_x =  indices[:, 0]
print(all_x)
all_y =  indices[:, 1]
print(all_y)

tf.Tensor([0 1 1 1 1], shape=(5,), dtype=int64)
tf.Tensor([3 0 1 2 3], shape=(5,), dtype=int64)


In [8]:
distance_all_x= all_x -centroidsx 
print("distance_all_x:", distance_all_x)

distance_all_x: tf.Tensor([-2 -1 -1 -1 -1], shape=(5,), dtype=int64)


In [9]:
distnace_all_x_squre =  tf.math.square(distance_all_x)
print("distnace_all_x_squre:", distnace_all_x_squre)

distnace_all_x_squre: tf.Tensor([4 1 1 1 1], shape=(5,), dtype=int64)


In [10]:
distance_all_y =  all_y-centroidsy
print("distance_all_y:", distance_all_y)

distance_all_y: tf.Tensor([ 0 -3 -2 -1  0], shape=(5,), dtype=int64)


In [11]:
distnace_all_y_squre =  tf.math.square(distance_all_y)
print("distnace_all_y_squre:", distnace_all_y_squre)

distnace_all_y_squre: tf.Tensor([0 9 4 1 0], shape=(5,), dtype=int64)


In [14]:
all_squre_distance = distnace_all_x_squre + distnace_all_y_squre
print("all_squre_distance:", all_squre_distance)

all_squre_distance: tf.Tensor([ 4 10  5  2  1], shape=(5,), dtype=int64)


In [18]:
distances_all_nonzeros =  tf.math.sqrt(tf.cast(all_squre_distance, tf.float32))
print("distances_all_nonzeros", distances_all_nonzeros)

distances_all_nonzeros tf.Tensor([2.        3.1622777 2.236068  1.4142135 1.       ], shape=(5,), dtype=float32)


In [19]:
max_dis =  tf.math.reduce_max(distances_all_nonzeros)
print("max_dis:", max_dis)

max_dis: tf.Tensor(3.1622777, shape=(), dtype=float32)


In [14]:
a = tf.constant([0.5])
b =  tf.constant([0.4])

min = tf.math.reduce_min([a, b])
print(min)
max = tf.math.reduce_max([a, b])
print(max)

tf.Tensor(0.4, shape=(), dtype=float32)
tf.Tensor(0.5, shape=(), dtype=float32)
