In [1]:
import cv2
import numpy as np
from glob import glob
src_path_root=  "E:\\dataset\\SublingualVein\\TIASRGB2020\\inputs" # the image needed to be transfered color
des_path_root = "E:\\dataset\\SublingualVein\\TIASRGB2020\\val" # the reference corlor image

output_folder =  "E:\\dataset\\SublingualVein\\TIASRGB2020\\color_transfer_test_inputs"



raw_inputs_paths =  sorted(glob(des_path_root+ "/*.bmp"))
ref_val_inputs_paths =  sorted(glob(src_path_root+ "/*.bmp"))
print("found {} raw inputs".format(len(raw_inputs_paths)))
print("found {} raw val inputs".format(len(ref_val_inputs_paths)))



# image = cv2.imread(des_path)
# image = cv2.cvtColor(image,cv2.COLOR_BGR2LAB)
# original = cv2.imread(src_path)
# original = cv2.cvtColor(original,cv2.COLOR_BGR2LAB)
# avg = []
# std = []

def getavgstd_lists(image):
    avg = []
    std = []
    image_avg_l = np.mean(image[:,:,0])
    image_std_l = np.std(image[:,:,0])
    image_avg_a = np.mean(image[:,:,1])
    image_std_a = np.std(image[:,:,1])
    image_avg_b = np.mean(image[:,:,2])
    image_std_b = np.std(image[:,:,2])
    avg.append(image_avg_l)
    avg.append(image_avg_a)
    avg.append(image_avg_b)
    std.append(image_std_l)
    std.append(image_std_a)
    std.append(image_std_b)
    return (avg,std)

def get_avg_std_for_all(paths):
    all_image_avg_list = []
    all_image_std_list = []
    for i in range(len(paths)):
        image = cv2.imread(paths[i])
        image = cv2.cvtColor(image,cv2.COLOR_BGR2LAB)
        image_avg, image_std = getavgstd_lists(image)
        all_image_avg_list.append(image_avg)
        all_image_std_list.append(image_std)
    return all_image_avg_list, all_image_std_list

ref_all_image_avg_list, ref_all_image_std_list = get_avg_std_for_all(ref_val_inputs_paths) 
raw_all_image_avg_list, raw_all_image_std_list = get_avg_std_for_all(raw_inputs_paths) 
print("ref_std_avg_len：", len(ref_all_image_avg_list))
print("raw_std_avg_len：", len(raw_all_image_avg_list))
print("ref_all_image_avg_list：", ref_all_image_avg_list)

# for in range(len(ref_all_image_avg_list)):
#     ref_l_a_b_mean = 
    
# for i in range(len(raw_inputs_paths)):
#     image = cv2.imread(raw_inputs_paths[i])
#     image = cv2.cvtColor(image,cv2.COLOR_BGR2LAB)
#     original = cv2.imread(src_path)
#     original = cv2.cvtColor(original,cv2.COLOR_BGR2LAB)
#     image_avg,image_std = getavgstd(image)
#     original_avg,original_std = getavgstd(original)

# height,width,channel = image.shape
# for i in range(0,height):
#     for j in range(0,width):
#         for k in range(0,channel):
#             t = image[i,j,k]
#             t = (t-image_avg[k])*(original_std[k]/image_std[k]) + original_avg[k]
#             t = 0 if t<0 else t
#             t = 255 if t>255 else t
#             image[i,j,k] = t
# image = cv2.cvtColor(image,cv2.COLOR_LAB2BGR)
# cv2.imwrite('out.jpg',image)

found 3 raw inputs
found 219 raw val inputs
ref_std_avg_len： 219
raw_std_avg_len： 3
ref_all_image_avg_list： [[129.26098524305556, 128.4548963155864, 126.67840229552469], [125.68903308256174, 128.72762538580247, 126.77339313271605], [131.9078337191358, 127.9095100308642, 127.03402826003087], [130.31239920910494, 128.50469376929013, 126.58478298611111], [133.66311631944444, 128.17317949459877, 126.82448688271604], [132.32948398919754, 128.1230434992284, 126.83826388888889], [131.74156828703704, 127.96510320216049, 127.27951774691358], [134.0862818287037, 127.48511091820987, 127.16554735725309], [133.64249180169753, 127.64057146990741, 126.52069492669753], [130.44721016589506, 128.0940586419753, 126.82222029320988], [129.2487562692901, 128.71662422839506, 126.48566936728395], [128.8003655478395, 128.39635175540124, 126.20347222222222], [124.5682209683642, 128.71963638117285, 126.64719232253087], [130.62441550925925, 128.35718171296296, 126.67747926311728], [123.66309220679013, 128.6025588

In [2]:

ref_all_image_avg_list_np =  np.array(ref_all_image_avg_list)
ref_all_image_std_list_np =  np.array(ref_all_image_std_list)
print("ref_all_image_avg_list_np:", ref_all_image_avg_list_np)
print("ref_all_image_std_list_np:", ref_all_image_std_list_np)
print("ref_all_image_avg_list_np.shape:", ref_all_image_avg_list_np.shape)
ref_all_image_l_a_b_avg_mean =  np.mean(ref_all_image_avg_list_np, axis = 0)
print("ref_all_image_l_a_b_mean:", ref_all_image_l_a_b_avg_mean)
ref_all_image_l_a_b_avg_std =  np.mean(ref_all_image_std_list_np, axis = 0)
print("ref_all_image_l_a_b_mean:", ref_all_image_l_a_b_avg_std)

ref_all_image_avg_list_np: [[129.26098524 128.45489632 126.6784023 ]
 [125.68903308 128.72762539 126.77339313]
 [131.90783372 127.90951003 127.03402826]
 [130.31239921 128.50469377 126.58478299]
 [133.66311632 128.17317949 126.82448688]
 [132.32948399 128.1230435  126.83826389]
 [131.74156829 127.9651032  127.27951775]
 [134.08628183 127.48511092 127.16554736]
 [133.6424918  127.64057147 126.52069493]
 [130.44721017 128.09405864 126.82222029]
 [129.24875627 128.71662423 126.48566937]
 [128.80036555 128.39635176 126.20347222]
 [124.56822097 128.71963638 126.64719232]
 [130.62441551 128.35718171 126.67747926]
 [123.66309221 128.60255883 126.82760368]
 [124.2283425  128.50143663 127.09935619]
 [127.57484086 127.93791184 126.95813995]
 [125.71049142 128.3700299  127.22092062]
 [122.63153839 128.50726177 127.10026669]
 [124.92068528 129.11786314 127.16832321]
 [126.33521943 129.03827257 126.86185233]
 [130.57790557 128.39813802 126.51498457]
 [126.23927807 128.87921345 126.41805797]
 [131.2

In [3]:
# start to convert all the images  from the raw inputs
import os
len_raw_inputs =  len(raw_all_image_avg_list)
print("len_raw_inputs:", len_raw_inputs)
for L in range(len_raw_inputs):
    image = cv2.imread(raw_inputs_paths[L])
    image = cv2.cvtColor(image,cv2.COLOR_BGR2LAB)
    height,width,channel = image.shape
    for i in range(0,height):
        for j in range(0,width):
            for k in range(0,channel):
                t = image[i,j,k]
                t = (t-raw_all_image_avg_list[L][k])*(ref_all_image_l_a_b_avg_std[k]/raw_all_image_std_list[L][k]) + ref_all_image_l_a_b_avg_mean[k]
                t = 0 if t<0 else t
                t = 255 if t>255 else t
                image[i,j,k] = t
    image = cv2.cvtColor(image,cv2.COLOR_LAB2BGR)
    
    filename = os.path.splitext(os.path.basename(raw_inputs_paths[L]))[0]
    print("filename:", filename)
    output_file_name = "color_tr_"+filename
    print("output_file_name:", output_file_name)
    cv2.imwrite(output_folder + "/" + output_file_name + ".bmp",image)

len_raw_inputs: 3
filename: 167_1558
output_file_name: color_tr_167_1558
filename: 168_1436
output_file_name: color_tr_168_1436
filename: 172-141
output_file_name: color_tr_172-141
