In [7]:
import cv2
import numpy as np
from glob import glob
des_path_root =  "E:\\dataset\\SublingualVein\\TIASRGB2020\\inputs" # the image needed to be transfered color
src_path_root = "E:\\dataset\\SublingualVein\\TIASRGB2020\\val" # the reference corlor image

output_folder =  "E:\dataset\SublingualVein\TIASRGB2020\color_transfer_output"



raw_inputs_paths =  sorted(glob(des_path_root+ "/*.bmp"))
ref_val_inputs_paths =  sorted(glob(src_path_root+ "/*.bmp"))
print("found {} raw inputs".format(len(raw_inputs_paths)))
print("found {} raw val inputs".format(len(ref_val_inputs_paths)))



# image = cv2.imread(des_path)
# image = cv2.cvtColor(image,cv2.COLOR_BGR2LAB)
# original = cv2.imread(src_path)
# original = cv2.cvtColor(original,cv2.COLOR_BGR2LAB)
# avg = []
# std = []

def getavgstd_lists(image):
    avg = []
    std = []
    image_avg_l = np.mean(image[:,:,0])
    image_std_l = np.std(image[:,:,0])
    image_avg_a = np.mean(image[:,:,1])
    image_std_a = np.std(image[:,:,1])
    image_avg_b = np.mean(image[:,:,2])
    image_std_b = np.std(image[:,:,2])
    avg.append(image_avg_l)
    avg.append(image_avg_a)
    avg.append(image_avg_b)
    std.append(image_std_l)
    std.append(image_std_a)
    std.append(image_std_b)
    return (avg,std)

def get_avg_std_for_all(paths):
    all_image_avg_list = []
    all_image_std_list = []
    for i in range(len(paths)):
        image = cv2.imread(paths[i])
        image = cv2.cvtColor(image,cv2.COLOR_BGR2LAB)
        image_avg, image_std = getavgstd_lists(image)
        all_image_avg_list.append(image_avg)
        all_image_std_list.append(image_std)
    return all_image_avg_list, all_image_std_list

ref_all_image_avg_list, ref_all_image_std_list = get_avg_std_for_all(ref_val_inputs_paths) 
raw_all_image_avg_list, raw_all_image_std_list = get_avg_std_for_all(raw_inputs_paths) 
print("ref_std_avg_len：", len(ref_all_image_avg_list))
print("raw_std_avg_len：", len(raw_all_image_avg_list))
print("ref_all_image_avg_list：", ref_all_image_avg_list)

# for in range(len(ref_all_image_avg_list)):
#     ref_l_a_b_mean = 
    
# for i in range(len(raw_inputs_paths)):
#     image = cv2.imread(raw_inputs_paths[i])
#     image = cv2.cvtColor(image,cv2.COLOR_BGR2LAB)
#     original = cv2.imread(src_path)
#     original = cv2.cvtColor(original,cv2.COLOR_BGR2LAB)
#     image_avg,image_std = getavgstd(image)
#     original_avg,original_std = getavgstd(original)

# height,width,channel = image.shape
# for i in range(0,height):
#     for j in range(0,width):
#         for k in range(0,channel):
#             t = image[i,j,k]
#             t = (t-image_avg[k])*(original_std[k]/image_std[k]) + original_avg[k]
#             t = 0 if t<0 else t
#             t = 255 if t>255 else t
#             image[i,j,k] = t
# image = cv2.cvtColor(image,cv2.COLOR_LAB2BGR)
# cv2.imwrite('out.jpg',image)

found 219 raw inputs
found 3 raw val inputs
ref_std_avg_len： 3
raw_std_avg_len： 219
ref_all_image_avg_list： [[81.44306716918945, 140.26250152587892, 141.14012451171874], [53.904693603515625, 138.1077880859375, 135.6070640563965], [47.26734161376953, 139.926220703125, 132.12427368164063]]


In [14]:

ref_all_image_avg_list_np =  np.array(ref_all_image_avg_list)
ref_all_image_std_list_np =  np.array(ref_all_image_std_list)
print("ref_all_image_avg_list_np:", ref_all_image_avg_list_np)
print("ref_all_image_std_list_np:", ref_all_image_std_list_np)
print("ref_all_image_avg_list_np.shape:", ref_all_image_avg_list_np.shape)
ref_all_image_l_a_b_avg_mean =  np.mean(ref_all_image_avg_list_np, axis = 0)
print("ref_all_image_l_a_b_mean:", ref_all_image_l_a_b_avg_mean)
ref_all_image_l_a_b_avg_std =  np.mean(ref_all_image_std_list_np, axis = 0)
print("ref_all_image_l_a_b_mean:", ref_all_image_l_a_b_avg_std)

ref_all_image_avg_list_np: [[ 81.44306717 140.26250153 141.14012451]
 [ 53.9046936  138.10778809 135.60706406]
 [ 47.26734161 139.9262207  132.12427368]]
ref_all_image_std_list_np: [[40.3079151   6.33925695 10.99890354]
 [39.04905654  6.66024467  9.92382907]
 [28.78133762  5.91738854  6.02338552]]
ref_all_image_avg_list_np.shape: (3, 3)
ref_all_image_l_a_b_mean: [ 60.8717008  139.4321701  136.29048742]
ref_all_image_l_a_b_mean: [36.04610308  6.30563005  8.98203938]


In [21]:
# start to convert all the images  from the raw inputs
import os
len_raw_inputs =  len(raw_all_image_avg_list)
print("len_raw_inputs:", len_raw_inputs)
for L in range(len_raw_inputs):
    image = cv2.imread(raw_inputs_paths[L])
    image = cv2.cvtColor(image,cv2.COLOR_BGR2LAB)
    height,width,channel = image.shape
    for i in range(0,height):
        for j in range(0,width):
            for k in range(0,channel):
                t = image[i,j,k]
                t = (t-raw_all_image_avg_list[L][k])*(ref_all_image_l_a_b_avg_std[k]/raw_all_image_std_list[L][k]) + ref_all_image_l_a_b_avg_mean[k]
                t = 0 if t<0 else t
                t = 255 if t>255 else t
                image[i,j,k] = t
    image = cv2.cvtColor(image,cv2.COLOR_LAB2BGR)
    
    filename = os.path.splitext(os.path.basename(raw_inputs_paths[L]))[0]
    print("filename:", filename)
    output_file_name = "color_tr_"+filename
    print("output_file_name:", output_file_name)
    cv2.imwrite(output_folder + "/" + output_file_name + ".bmp",image)

len_raw_inputs: 219
filename: 1002dozono01 (1)
output_file_name: color_tr_1002dozono01 (1)
filename: 1002dozono01 (10)
output_file_name: color_tr_1002dozono01 (10)
filename: 1002dozono01 (2)
output_file_name: color_tr_1002dozono01 (2)
filename: 1002dozono01 (3)
output_file_name: color_tr_1002dozono01 (3)
filename: 1002dozono01 (4)
output_file_name: color_tr_1002dozono01 (4)
filename: 1002dozono01 (5)
output_file_name: color_tr_1002dozono01 (5)
filename: 1002dozono01 (6)
output_file_name: color_tr_1002dozono01 (6)
filename: 1002dozono01 (7)
output_file_name: color_tr_1002dozono01 (7)
filename: 1002dozono01 (8)
output_file_name: color_tr_1002dozono01 (8)
filename: 1002dozono01 (9)
output_file_name: color_tr_1002dozono01 (9)
filename: Seki_0
output_file_name: color_tr_Seki_0
filename: Seki_01a1
output_file_name: color_tr_Seki_01a1
filename: Seki_01a10
output_file_name: color_tr_Seki_01a10
filename: Seki_01a2
output_file_name: color_tr_Seki_01a2
filename: Seki_01a3
output_file_name: color_