In [1]:
from __future__ import print_function
import torch

An uninitialized matrix is declared, but does not contain definite known values before it is used. When an uninitialized matrix is created, whatever values were in the allocated memory at the time will appear as the initial values.

Construct a 5x3 matrix, uninitialized:

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[2.9722e-24, 8.2396e-43, 2.9722e-24],
        [8.2396e-43, 2.9725e-24, 8.2396e-43],
        [2.9725e-24, 8.2396e-43, 2.9722e-24],
        [8.2396e-43, 2.9722e-24, 8.2396e-43],
        [2.9725e-24, 8.2396e-43, 2.9725e-24]])


Construct a randomly initialized matrix:

In [4]:
x = torch.rand(5, 3)
print(x)


tensor([[0.9226, 0.3377, 0.4519],
        [0.8717, 0.0870, 0.0279],
        [0.5362, 0.7061, 0.1926],
        [0.9233, 0.6591, 0.6088],
        [0.2388, 0.3751, 0.9605]])


Construct a matrix filled zeros and of dtype long:

In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:

In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [8]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)       

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.0545, -0.3312, -0.2447],
        [-0.0541,  2.4685, -0.3975],
        [-0.1119, -0.7630,  0.7097],
        [-0.7080,  0.4374, -0.0744],
        [-0.4673, -0.2801, -0.4373]])


Operations
There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation.

Addition: syntax 1

In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.5955, -0.0661,  0.6039],
        [ 0.5986,  2.7528, -0.0259],
        [ 0.4812, -0.1968,  1.2516],
        [-0.4961,  1.3104,  0.5414],
        [-0.3260,  0.2844,  0.2713]])


Addition: syntax 2

In [10]:
print(torch.add(x, y))

tensor([[ 1.5955, -0.0661,  0.6039],
        [ 0.5986,  2.7528, -0.0259],
        [ 0.4812, -0.1968,  1.2516],
        [-0.4961,  1.3104,  0.5414],
        [-0.3260,  0.2844,  0.2713]])


Addition: providing an output tensor as argument

In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.5955, -0.0661,  0.6039],
        [ 0.5986,  2.7528, -0.0259],
        [ 0.4812, -0.1968,  1.2516],
        [-0.4961,  1.3104,  0.5414],
        [-0.3260,  0.2844,  0.2713]])


Addition: in-place

In [13]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.5955, -0.0661,  0.6039],
        [ 0.5986,  2.7528, -0.0259],
        [ 0.4812, -0.1968,  1.2516],
        [-0.4961,  1.3104,  0.5414],
        [-0.3260,  0.2844,  0.2713]])


NOTE

Any operation that mutates（变异） a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.

you can use standard NumPy-like indexing with all bells and whistles!

In [14]:
print(x[:, 1])

tensor([-0.3312,  2.4685, -0.7630,  0.4374, -0.2801])


Resizing: If you want to resize/reshape tensor, you can use torch.view:

In [15]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use .item() to get the value as a Python number

In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.6458])
-0.6458309888839722
